mod common;
use cmsg::{verify_admission, Member};
use common::{grant, sign, trust};
#[test]
fn valid_signed_community_identity_and_chat_key_are_bound() {
    let key = [23; 32];
    let grant = grant(&key, 7);
    assert_eq!(
        verify_admission(&grant, &trust(), &key, 100).unwrap(),
        grant.member_id
    );
}
#[test]
fn altered_identity_key_policy_issuer_and_expiry_are_rejected() {
    let key = [23; 32];
    let original = grant(&key, 7);
    assert!(verify_admission(&original, &trust(), &[24; 32], 100).is_err());
    assert!(verify_admission(&original, &trust(), &key, original.expires_at).is_err());
    assert!(verify_admission(&original, &trust(), &key, 0).is_err());
    let mut changed = original.clone();
    changed.member_id = grant(&key, 8).member_id;
    assert!(verify_admission(&changed, &trust(), &key, 100).is_err());
    changed = original.clone();
    changed.community_id = "different-community".into();
    sign(&mut changed);
    assert!(verify_admission(&changed, &trust(), &key, 100).is_err());
    changed = original.clone();
    changed.policy_digest = grant(&[1; 32], 0).chat_public_key;
    sign(&mut changed);
    assert!(verify_admission(&changed, &trust(), &key, 100).is_err());
    changed = original.clone();
    changed.issuer_key_id = changed.member_id.clone();
    sign(&mut changed);
    assert!(verify_admission(&changed, &trust(), &key, 100).is_err());
    let mut other = trust();
    other.issuer_public_key = [10; 32];
    assert!(verify_admission(&original, &other, &key, 100).is_err());
}
#[test]
fn unadmitted_identity_cannot_create_a_group_or_key_package() {
    let mut member = Member::new().unwrap();
    assert!(member.create_group().is_err());
    assert!(member.key_package().is_err());
}
#[test]
fn an_identity_certificate_cannot_be_copied_onto_a_different_chat_key() {
    let a = common::member();
    let mut b = Member::new().unwrap();
    let certificate = grant(&a.chat_public_key(), 9);
    assert!(b.bind_admission(certificate, trust(), 100).is_err());
    assert!(b.key_package().is_err());
}
#[test]
fn another_communitys_valid_identity_cannot_join_this_group() {
    let mut a = common::member();
    a.create_group().unwrap();
    let mut b = Member::new().unwrap();
    let mut certificate = grant(&b.chat_public_key(), 9);
    let mut other_trust = trust();
    certificate.community_id = "another-community".into();
    other_trust.community_id = certificate.community_id.clone();
    sign(&mut certificate);
    b.bind_admission(certificate, other_trust, 100).unwrap();
    assert!(a.add(&b.key_package().unwrap()).is_err());
}
#[test]
fn malicious_welcome_does_not_destroy_a_valid_pending_key_package() {
    use openmls::prelude::*;
    use openmls_basic_credential::SignatureKeyPair;
    use openmls_rust_crypto::OpenMlsRustCrypto;
    use openmls_traits::OpenMlsProvider;
    use tls_codec::{Deserialize, Serialize};
    let mut receiver = common::member();
    let mut valid_inviter = common::member();
    valid_inviter.create_group().unwrap();
    let package = receiver.key_package().unwrap();
    let valid_welcome = valid_inviter.add(&package).unwrap().welcome;
    let provider = OpenMlsRustCrypto::default();
    let suite = Ciphersuite::MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519;
    let signer = SignatureKeyPair::new(suite.signature_algorithm()).unwrap();
    let credential = CredentialWithKey {
        credential: BasicCredential::new(b"self-asserted identity without cvld proof".to_vec())
            .into(),
        signature_key: signer.to_public_vec().into(),
    };
    let config = MlsGroupCreateConfig::builder()
        .ciphersuite(suite)
        .use_ratchet_tree_extension(true)
        .wire_format_policy(PURE_CIPHERTEXT_WIRE_FORMAT_POLICY)
        .build();
    let mut malicious = MlsGroup::new(&provider, &signer, &config, credential).unwrap();
    let package = KeyPackageIn::tls_deserialize_exact(&package)
        .unwrap()
        .validate(provider.crypto(), ProtocolVersion::Mls10)
        .unwrap();
    let (_, wrong_welcome, _) = malicious
        .add_members(&provider, &signer, &[package])
        .unwrap();
    assert!(receiver
        .join(&wrong_welcome.tls_serialize_detached().unwrap())
        .is_err());
    receiver
        .join(&valid_welcome)
        .expect("invalid welcome must not consume key-package secrets");
}
#[test]
fn verifies_the_javascript_cvld_issuer_fixture_byte_for_byte() {
    use data_encoding::BASE64URL_NOPAD;
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Fixture {
        public_key: String,
        now: u64,
        grant: cmsg::AdmissionGrant,
    }
    // Generated by corbet-labs/cvld's admission test with a public RFC8032 key.
    let fixture: Fixture =
        serde_json::from_str(include_str!("fixtures/admission-v1.json")).unwrap();
    let trust = cmsg::AdmissionTrust {
        community_id: fixture.grant.community_id.clone(),
        policy_digest: fixture.grant.policy_digest.clone(),
        issuer_public_key: BASE64URL_NOPAD
            .decode(fixture.public_key.as_bytes())
            .unwrap()
            .try_into()
            .unwrap(),
    };
    let chat_key = BASE64URL_NOPAD
        .decode(fixture.grant.chat_public_key.as_bytes())
        .unwrap();
    assert_eq!(
        verify_admission(&fixture.grant, &trust, &chat_key, fixture.now).unwrap(),
        fixture.grant.member_id
    );
}
